### ISSUE TITLE
Services Component

### ISSUE THREAD

**Issue by evgimov** [ivanvillacreative/simple-reservation#40]
<img width="377" alt="screen shot 2018-08-25 at 1 55 07 pm" src="https://user-images.githubusercontent.com/9972541/44622503-85d50800-a86e-11e8-8b7f-6a7c657a4c27.png">

**Comment by ivanvillacreative** [comment]
@mishcodes  this is the component that has a lot of the functionality we need

https://react-slick.neostack.com/

**Comment by evgimov** [comment]
The services component was refactored, added componentDidMount method with making a query inside to get all services from the firestore database, added layout to display the services within the Slider component (imported it from react-slick library - https://react-slick.neostack.com/docs/get-started) and added styling to the component
