### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by ivanvillacreative** [ivanvillacreative/simple-reservation#5]
I have started creating some wireframes for the reservation view, these are basic but hopefully will help get conversation going [reservation-mobile](https://xd.adobe.com/view/4060e5b2-dfe5-4329-6b63-c86c89300d45-3651/)

**Comment by evgimov** [comment]
I think you missed the field for the name of a client.

**Comment by evgimov** [comment]
Can you please also add "confirm" and "cancel" buttons for the text message mockup?

**Comment by ivanvillacreative** [comment]
@evgimov Good catch, I will make updates later today.

**Comment by ivanvillacreative** [comment]
I added the name field in the mock up. I don't think we need a text message mock up as that will only be a text and limited to characters
